package com.shine.service.impl;

import java.util.List;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.shine.model.DataConnection;
import com.shine.service.DataConnectionService;

/**
 * Generated by Blade. 2017-08-16 09:50:09
 */
public class DataConnectionServiceImpl extends BaseService<DataConnection> implements DataConnectionService {

	Blade blade = Blade.create(DataConnection.class);

	@Override
	public List<DataConnection> listDesc() {
		return blade.findBy("id,description", "1=1", null);
	}

}
