package com.shine.service.impl;

import com.core.base.service.impl.BaseService;
import com.shine.model.DbSql;
import com.shine.service.DbSqlService;

/**
 * Generated by Blade. 2017-08-16 09:50:09
 */
public class DbSqlServiceImpl extends BaseService<DbSql> implements DbSqlService {

}
