package com.shine.service.impl;

import java.util.List;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.core.dao.Db;
import com.core.toolbox.Record;
import com.shine.model.Doctor;
import com.shine.model.QueueType;
import com.shine.service.DoctorService;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
public class DoctorServiceImpl extends BaseService<Doctor> implements DoctorService {

	Blade blade = Blade.create(Doctor.class);

	// \u67E5\u8BE2\u6240\u6709\u961F\u5217\u540D\u79F0
	@Override
	public List<Record> queryQueueTypeName() {
		return Blade.create(QueueType.class).findBy("queue_type_id,name", " where 1=1", QueueType.class);
	}

	// \u67E5\u8BE2\u533B\u751F\u767B\u9646\u5DE5\u53F7
	@Override
	public Doctor findByLogin_id(String login_id) {
		return blade.findFirstBy("login_id=#{login_id}", Record.create().set("login_id", login_id));
	}

	@Override
	public List<Record> list_doctor() {
		return blade.findAll();
	}

	@Override
	public List<Record> call_doctor_queueType_name(String login_id, String ip, String type) {
		String sql = "";
		if ("1".equals(type)) {
			sql += Blade.dao().getScript("Doctor.calldoctorname").getSql();
		} else if ("2".equals(type)) {
			sql += Blade.dao().getScript("Pager.callpagername").getSql();
		}
		return Db.init().selectList(sql, Record.create().set("login_id", login_id).set("ip", ip));
	}

	@Override
	public Record queryByip(String ip) {
		String sql = Blade.dao().getScript("Doctor.queryByip").getSql();
		return Db.init().selectOne(sql, Record.create().set("ip", ip));

	}

	@Override
	public List<Record> queryByipAll(String ip) {
		String sql = Blade.dao().getScript("Doctor.queryByip").getSql();
		return Db.init().selectList(sql, Record.create().set("ip", ip));

	}

	
}
