package com.shine.service.impl;

import com.core.base.service.impl.BaseService;
import com.shine.model.Item;
import com.shine.service.ItemService;

/**
 * Generated by Blade. 2017-08-17 14:14:07
 */
public class ItemServiceImpl extends BaseService<Item> implements ItemService {

}
