package com.shine.service.impl;

import java.util.List;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.core.dao.Db;
import com.core.toolbox.Record;
import com.shine.model.Pager2queuetype;
import com.shine.service.Pager2queuetypeService;

/**
 * Generated by Blade. 2017-08-09 15:50:39
 */
public class Pager2queuetypeServiceImpl extends BaseService<Pager2queuetype> implements Pager2queuetypeService {

	@Override
	public List<Record> pager_paiban(String ip) {
		String sql = Blade.dao().getScript("Doctor2queuetype.pager_paiban").getSql();
		return Db.init().selectList(sql, Record.create().set("ip", ip));
	}

	@Override
	public Record querypagerpaiban(String login_id) {
		String sql = Blade.dao().getScript("Pager2queuetype.querypagerpaiban").getSql();
		return Db.init().selectOne(sql, Record.create().set("login_id", login_id));
	}

}
