package com.shine.service.impl;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.core.dao.Db;
import com.core.toolbox.Record;
import com.shine.model.Pager;
import com.shine.model.Triage;
import com.shine.service.PagerService;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
public class PagerServiceImpl extends BaseService<Pager> implements PagerService {

	Blade blade = Blade.create(Pager.class);
	String nowtimes = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss:SSSS").format(new Date());

	// \u67E5\u8BE2\u6240\u6709\u5206\u8BCA\u53F0\u540D\u79F0
	@Override
	public List<Record> queryTriageName() {
		return Blade.create(Triage.class).findBy("triage_id,name", " where 1=1", Triage.class);
	}

	// \u6839\u636E\u53EB\u53F7\u5668\u540D\u79F0\u67E5\u8BE2
	@Override
	public Pager findByName(String name) {
		return blade.findFirstBy("name=#{name}", Record.create().set("name", name));
	}

	// \u6839\u636Eip\u67E5\u8BE2
	@Override
	public Pager findByIP(String ip) {
		return blade.findFirstBy("ip=#{ip}", Record.create().set("ip", ip));
	}

	@Override
	public int updatepagerinsert(String login_id, String ip) {
		String sql = Blade.dao().getScript("Pager.updatepagerinsert").getSql();
		return Db.init().update(sql, Record.create().set("login_id", login_id).set("ip", ip));
	}

	@Override
	public int updatedoctorid(String pager_ip, String login_id) {
		String sql = Blade.dao().getScript("Pager.updatedoctorid").getSql();
		return Db.init().update(sql, Record.create().set("pager_ip", pager_ip).set("login_id", login_id));
	}

	@Override
	public Record call_login(String login_id) {
		String sql = Blade.dao().getScript("Pager.call_login").getSql();
		return Db.init().selectOne(sql, Record.create().set("login_id", login_id));
	}

	@Override
	public boolean updatepagerdelete(String ip) {
		return blade.updateBy("doctor_id=NULL", "ip=#{ip}", Record.create().set("ip", ip));
	}

	@Override
	public int logout(String pager_ip, String login_id) {
		String sql = Blade.dao().getScript("Pager.logout").getSql();
		return Db.init().update(sql, Record.create().set("pager_ip", pager_ip).set("login_id", login_id));
	}

	@Override
	public Record findip(String ip) {
		return blade.findOneColBy("id,display_name", "ip=#{ip}", Record.create().set("ip", ip));
	}
   @Override
   public int loginoutall()
   		{return Db.init().update("update pager set doctor_id=null,call_pass_first_flag=0,call_pass_rule_flag=0,call_return_first_flag=0,call_return_rule_flag=0,call_late_first_flag=0,call_late_rule_flag=0,call_first_first_flag=0,call_first_rule_flag=0,call_first_rule_flag2=0",null);}
}
