package com.shine.service.impl;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.core.dao.Db;
import com.core.toolbox.Record;
import com.shine.model.Pager2terminal;
import com.shine.service.Pager2terminalService;

/**
 * Generated by Blade. 2017-08-12 15:10:05
 */
public class Pager2terminalServiceImpl extends BaseService<Pager2terminal> implements Pager2terminalService {

	@Override
	public Record findByIP(String ip) {
		String sql = Blade.dao().getScript("Pager2terminal.findByIP").getSql();
		return Db.init().selectOne(sql, Record.create().set("ip", ip));
	}

}
