package com.shine.service.impl;

import java.util.List;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.core.dao.Db;
import com.core.toolbox.Record;
import com.shine.model.PatientCode;
import com.shine.service.PatientCodeService;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
public class PatientCodeServiceImpl extends BaseService<PatientCode> implements PatientCodeService {

	@Override
	public int deletecode() {
		String sql = Blade.dao().getScript("PatientCode.deleteCode").getSql();
		return Db.init().delete(sql, null);
		//return Blade.create(PatientCode.class).deleteBy("1=1", null);
	}

	@Override
	public List<Record> listall() {
		return Blade.create(PatientCode.class).findAll();
	}

}
