package com.shine.service.impl;

import java.util.List;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.shine.model.Source;
import com.shine.service.SourceService;

/**
 * Generated by Blade. 2017-08-17 14:14:06
 */
public class SourceServiceImpl extends BaseService<Source> implements SourceService {

	@Override
	public List<Source> listDesc() {
		return Blade.create(Source.class).findBy("id,description", "1=1", null);
	}

}
