package com.shine.service.impl;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.core.dao.Db;
import com.core.toolbox.Record;
import com.shine.model.Terminal;
import com.shine.service.TerminalService;

/**
 * Generated by Blade. 2017-08-12 15:10:04
 */
public class TerminalServiceImpl extends BaseService<Terminal> implements TerminalService {

	Blade blade = Blade.create(Terminal.class);

	@Override
	public Terminal findbyip(String ip) {
		return blade.findFirstBy("ip=#{ip}", Record.create().set("ip", ip));
	}

	@Override
	public Record findbytriageip(String ip) {
		String sql = Blade.dao().getScript("Terminal.findbytriageip").getSql();
		return Db.init().selectOne(sql, Record.create().set("ip", ip));
	}
	@Override
	public Record findtriageBytemIP(String ip) {
		String sql = Blade.dao().getScript("Terminal.findtriageBytemIP").getSql();
		return Db.init().selectOne(sql, Record.create().set("temIp", ip));
	}

	@Override
	public String getpageripbyterip(String ip) {
		String sql = Blade.dao().getScript("Terminal.getpageripbyterip").getSql();
		return Db.init().selectOne(sql, Record.create().set("ip", ip)).getStr("ip");
	}
	@Override
	public  void  addterminal(String ip,String name) {
		String sql = Blade.dao().getScript("Terminal.addterminal").getSql();
		Db.init().insert(sql, Record.create().set("ip", ip).set("name", name).set("display_name",name));
	}
	@Override
	public  int  edittriage(String ids,String triage_id) {
		String sql = Blade.dao().getScript("Terminal.edittriage").getSql();
		return Db.init().update(sql, Record.create().set("ids", ids).set("id", triage_id));
	}
}
