package com.shine.service.impl;

import java.util.List;

import com.core.base.service.impl.BaseService;
import com.core.dao.Blade;
import com.core.dao.Db;
import com.core.toolbox.Record;
import com.shine.model.Triage;
import com.shine.service.TriageService;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
public class TriageServiceImpl extends BaseService<Triage> implements TriageService {

	Blade blade = Blade.create(Triage.class);

	// list\u67E5\u8BE2\u6CA1\u6709\u503C\u8BBE\u7F6E\u4E3B\u952E\u4ECE1\u91CD\u65B0\u5F00\u59CB
	@Override
	public List<Record> queryAll() {
		return blade.findAll();
	}

	// \u6839\u636E\u5206\u8BCA\u53F0\u540D\u79F0\u67E5\u8BE2
	@Override
	public Triage queryTriageName(String triageName) {
		return blade.findFirstBy("name=#{name}", Record.create().set("name", triageName));
	}

	// \u6839\u636E\u5206\u8BCA\u53F0ip\u67E5\u8BE2
	@Override
	public Triage queryTriageIp(String triageIp) {
		return blade.findFirstBy("ip=#{ip}", Record.create().set("ip", triageIp));
	}

	// \u5206\u8BCA\u53F0\u767B\u9646
	@Override
	public Triage queryLogin(String ip, String password) {
		String sql = "select * from triage where ip='" + ip + "' and triage_pwd='" + password + "'";
		return blade.findFirst(sql, null);
	}

	@Override
	public List<Record> queryByQueueType(String ip) {
		String sql = Blade.dao().getScript("Triage.queryByQueueType").getSql();
		return Db.init().selectList(sql, Record.create().set("ip", ip));
	}

	@Override
	public Record findtypelogin_id(String login_id) {
		String sql = Blade.dao().getScript("Triage.findtypelogin_id").getSql();
		return Db.init().selectOne(sql, Record.create().set("login_id", login_id));
	}

	@Override
	public Record findbypagerip(String triageIp) {
		String sql = Blade.dao().getScript("Triage.findbypagerip").getSql();//
		return Db.init().selectOne(sql, Record.create().set("triageIp", triageIp));
	}
	@Override
	public Record findbytriageip(String triageIp) {
		String sql = Blade.dao().getScript("Triage.findbytriageip").getSql();//
		return Db.init().selectOne(sql, Record.create().set("triageIp", triageIp));
	}

	@Override
	public Record  findtriageBytemIP(String temIp) 
	{
		String sql = Blade.dao().getScript("Triage.findtriageBytemIP").getSql();//
		return Db.init().selectOne(sql, Record.create().set("temIp", temIp));
	}

}
