package com.shine.service;

import java.util.List;

import com.core.base.service.IService;
import com.shine.model.DataConnection;

/**
 * Generated by Blade. 2017-08-16 09:50:09
 */
public interface DataConnectionService extends IService<DataConnection> {

	public List<DataConnection> listDesc();
}
