package com.shine.service;

import com.core.base.service.IService;
import com.shine.model.DbSql;

/**
 * Generated by Blade. 2017-08-16 09:50:09
 */
public interface DbSqlService extends IService<DbSql> {

}
