package com.shine.service;

import java.util.List;

import com.core.base.service.IService;
import com.core.toolbox.Record;
import com.shine.model.Doctor2queuetype;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
public interface Doctor2queuetypeService extends IService<Doctor2queuetype> {

	public List<Record> findDoctorPaiban(String ip);

	public boolean update_rdq(String ids, String onduty);

	public int delete_pb(String ids);

	public Record finddoctorandqueuetypeid(String doctor_id, String queue_type_id);

	public Record querydoctorpaiban(String login_id);

	public List<Record> findInt(int doctor_id, int queue_type_id);

	public List<Record> findeDoctorPaibanByWeek(String week);
	
	public List<Record> paiban_week_doctor(String login_ids);
	
	public List<Record> paiban_week_doctor_page(String login_ids,int begin,int size);
}
