package com.shine.service;

import com.core.base.service.IService;
import com.shine.model.Item;

/**
 * Generated by Blade. 2017-08-17 14:14:07
 */
public interface ItemService extends IService<Item> {

}
