package com.shine.service;

import java.util.List;

import com.core.base.service.IService;
import com.core.toolbox.Record;
import com.shine.model.Pager2queuetype;

/**
 * Generated by Blade. 2017-08-09 15:50:39
 */
public interface Pager2queuetypeService extends IService<Pager2queuetype> {

	public List<Record> pager_paiban(String ip);

	public Record querypagerpaiban(String login_id);
}
