package com.shine.service;

import java.util.List;
import java.util.Map;

import com.core.base.service.IService;
import com.core.toolbox.Record;
import com.shine.model.PatientQueue;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
public interface PatientQueueService extends IService<PatientQueue> {

	public List<Record> findpatientqueuetypeid(String queue_type_id);

	public boolean updateisdisplay(int queue_type_id, String type, String oprtime);

	public List<Record> listPatient(String queueTypeId);

	public List<Record> listPatient_lock(String queueTypeId);
	
	public List<Record> listPatient_agin(String queueTypeId);
	
	public List<Record> listPatient_first(String queueTypeId);
	
	public List<Record> listPatient_late(String queueTypeId);
	
	public List<Record> listPatient_pass(String queueTypeId);

	public List<Record> listPatient_already(String queueTypeId);

	public List<Record> listPatient_passno(String queueTypeId);
	public List<Record> listPatient_nodisplay(String queueTypeId);

	public PatientQueue findByQueueNum(String QueueNumber);

	public boolean patientFirst(String ids);
	
	public boolean patientFirstByPagerList(String pager_id,String ids);
	
	public Record getPagerIsLogin(String ids);
	public Record getPagerIsLogin2(int ids);
	public List<Record> getFirstByQueutTypeID(int queue_type_id);
	public int updateFirstCallStatus(int v1,int v2,int id);
	
	public List<Record> getLateByQueutTypeID(int queue_type_id);
	
	
	public List<Record> findCode(String code, String ip);
	public List<Record> findCodePager(String code, String ip);
	
	public List<Record> findCodeThirdSelectPatient(String code, String ip);
	public List<Record> findCodePagerThirdSelectPatient(String code, String ip);
	
	public int  queuetypeisckinorder(String queue_type_id) ;
	
	public int findmaxregisteridbyisdisplay(String queue_type_id);
	public int findmaxregisteridbyisdisplayByPager(String queue_type_id);
	
	public int updatedisplaybyscan(int id);
	public int updatedisplaybyscan2(int id);
	public int updateFZbyscan(int id,String opr_time,String queue_type_id);
	public int  findmaxregisteridnow(String queue_type_id);
	public int updatedisplaybyscanreorder(String register_id,int id);

	public int updatepatientqueuedislpay(String code,String ip);

	public boolean NewlyDiagnosed(String ids);
	public boolean NewlyDiagnosedByPagerList(String pager_id,String ids);
	public boolean passed(String ids);
	public boolean passedByPagerList(String pager_id,String ids);
	public boolean visit(String queue_type_id,String ids);
	public boolean visitByPagerList(String pager_id,String ids);
	public boolean GreenChannel(String ids);
	public boolean GreenChannelByPagerList(String pager_id,String ids);
	public boolean delay(int times, String ids);

	public boolean Hang(String ids);
	
	public boolean HangByPagerList(String pager_id,String ids);
	
	public boolean baodaopager(String code,String queue_type_id);
	public boolean baodaopager2(String code,String queue_type_id,Integer r);
	public boolean baodaopager3(String code,String queue_type_id);
	public Record getpatientbypagerlist(String code,String queue_type_id);
	
	public Integer getylnmb(String queue_type_id,int ylh);
	
	
	public Record findmaxregisterid(String queue_type_id);
	public Record findmaxregisterid2(String queue_type_id);
	public Record findpagermaxregistreid(String queue_type_id);
	public Record findpagermaxregistreid2(String queue_type_id);

	public List<Record> maxregisterid(String queue_type_id);

	public boolean ReferralQueueType(String queue_type_id, String ids, String register_id, String doctor_id);

	public boolean ReferralQueueType2(String queue_type_id, String ids, String register_id);

	public List<Record> GetPatientByCodeTypeID(String queue_type_id,String code);
	
	public boolean ReferralQueueType3(String queue_type_id, String ids, String register_id, String doctor_id);

	public boolean ReferralQueueType4(String queue_type_id, String ids, String register_id);
	
	public boolean examinationdoctor(String doctor_id, String ids, String queue_type_id);

	public boolean examinationpager(String pager_id, String ids, String queue_type_id);

	public boolean noexamination(String ids, String type);

	public List<Record> finddoctorid(String queue_type_id, String type);

	public List<Record> list_doctor(String login_id, int queue_type_id);
	public List<Record> list_doctor_nodisplay(String login_id, int queue_type_id);
	
	
	

	public List<Record> list_pager(String ip, int queue_type_id);
	public List<Record> list_pager2(String ip, int queue_type_id);
	
	
	public List<Record> list_doctor_locked(String login_id, int queue_type_id);
	public List<Record> list_pager2_locked(String ip, int queue_type_id);

	public List<Record> list_call_patient_pass(int queue_type_id, String pager_ip, String type, String login_id);

	public List<Record> list_call_patient_was(int queue_type_id, String pager_ip, String type, String login_id);

	public List<Record> list_call_patient_over(int queue_type_id, String pager_ip, String type, String login_id,
			int doctor_id);

	public List<Record> list_call_patient_agin(int queue_type_id, String pager_ip, String type, String login_id,
			int doctor_id);
	public List<Record> list_call_patient_late(int queue_type_id, String pager_ip, String type, String login_id);
	public List<Record> list_call_patient_first(int queue_type_id, String pager_ip, String type, String login_id);

	public Record call_next_doctor(String queue_type_id, String pager_ip, String login_id, int doctor_id);

	public Record call_next_pager(String queue_type_id, String pager_ip, String login_id);

	public boolean update_patient_state(String pager_ip, String login_id, int id, int doctor_id);

	public Record select_patient_queue_id(String pager_ip, String login_id, String type);

	public Record recall(int patient_queue_id, String pager_ip, String login_id, String type);

	public int SetPatientState(int patient_queue_id, String pager_ip, String login_id, int state, String type,int queue_type_id);
	

	public Record call_select(String patient_queue_id, String queue_type_id, String pager_ip, String login_id,
			String type);
	
	public Record select_state_patient(String pager_ip, String login_id, String type);
	
	public List<Record> select_state_patient(String pager_ip, String login_id);

	public Record list_patient_visit(String queue_type_id);

	public List<PatientQueue> querydgtop10(String queue_type_id);

	public List<Record> list_patient_call(String ip);

	public List<Record> list_patient_call2(String ip);
	public List<Record> list_patient_call_pager(String ip);

	public boolean updatecontent(String id);
	public Integer updatecontent2(String ip);

	public List<Record> list_room_door(String doctor_id);

	public Record list_doctor_room_door_jz(String doctor_id, String ip);

	public Record list_pager_room_door_jz(String ip);

	public int updatecall(String doctor_id);

	public int updatecall2(String ip);

	public PatientQueue findByPatient_id(String patient_id);

	public List<Record> list_content_patient(String ip);

	public boolean update_istype();

	public int update_content(int queue_type_id, int id, String ip);

	public Record count_patient_doctor(String pager_ip, String login_id);

	public Record count_patient_pager(String pager_ip, String login_id);

	public Record GetStatistic(String queue_type_id, String pager_ip, String login_id);

	public List<Record> GetPatientList(String Queue_type_source_id, String pager_ip, String login_id);

	public int deletepatient();
	
	public Record checktab(String tabname);
	
	public int creattab(String tabname);
	
	public int syncPatientData(String tabname);

	public List<Record> querytable();

	public int deletepatientbyqueuetypeid(String queue_type_id);

	public List<Record> selectPatientDisplay(String ip);

	public int updatesetpatientdisplay(String id, String sort, String code);

	public Record selectlestpatientqueue(String source_code);

	public Record getqueuemaxregisterid(String queue_type_id);

	public List<Record> vistinglocaltion(String ip);

	public List<Record> listnextshowpager(String ip);

	public List<Record> listnextshowdoctor(String ip, String doctor_id);

	public int updatenextshow(String ip);
	public List<Record> selectpatientdoctor(String ip, String status);
	public List<Record> selectpatientpager(String ip, String status);
	public List<Record> selectpatientpager_locked(String ip);
	public List<Record> checkpagercalling(String ip);
	public List<Record> selectpatientpagerbypager(String ip, String status);
	//根据叫号器Id获取绑定队列患者，按Regsiter_id排序
	public List<Record> selectpatientpagerId(String id, String status);
	public List<Record> selectpatientpagerId_lock(String id);
	public List<Record> selectpatientpagerId_nodisplay(String id);
	//根据叫号器Id获取绑定队列患者，按操作时间排序
	public List<Record> selectpatientpagerId2(String id, String status);
	public List<Record> selectpatientpagerId2_locked(String id);
	public List<Record> selectpatientpagerId3(String id, String status);
	
	public List<Record> selectpatientteminal(String ip,String status);
	
	public Record selectpatientbycode(String ip, String code);

	public int callupdatestatusbypager(String pager_ip, String code, String status, String call, String content);

	public Record selectpatientbycodeandip(String pager_ip, String code);

	public int updatepatientpagercallerstatus(String key, String code, String ip);
	
	public int  updatepatientGHbyDoorscan(String code,String queue_type_id) ;

	public Record selectTriageRule(String queue_type_id);

	public int updatequeuetime(String queue_type_id, int time_was, int time_agin, int f_was, int f_agin,int time_late,int f_late);

	public Record selectQueueTime(String queue_type_id);

	public Record selectqueuetypeidbydoctor(int doctor_id);

	public Record selectTQrule(String ip);
	public Record selectTQrule2(String ip);
	public Record selectTQrule3(String queue_type_id,String type);
	public Record selectTQrule4(String id);

	public int updatepagertime(String ip, int f_was, int f_agin,int f_late,int f_first);

	public List<Record> selectpatientcallingpager(String ip, String status);
	
	public Record selectPatientBySourceCode(String queue_type_id,String source_code);
	
	public int  updateQuhaoIsdisplay(String id) ;
	
	public Record selectPatientbycode(String code,String queue_type_id) ;
	
	public Record selectPatientbyPagerIDAndCode(String queue_type_id,String code);
	public int updatePatientbyPagerIDandCode(String id,String code ,int state,String opr_time);
	
	public int updatePatientLateLock(String idcode,String type,String time);
	
	public List<Record> selectIsBegin(byte type,String id);
	
	public List<Record> selectPassByTer(String type,String ip);
	
	public int getReserveMaxNmb(String queue_type_id,String date);
	
	public boolean InsertReserve(String queue_type_id,String patient_id,String patient_name,String patient_source_code,String reserve_id,String reserve_time,String begin_time,String end_time);
	
	public int copyReservePatient();

	public int insertPatient(Record map);
}
