package com.shine.service;

import java.util.List;

import com.core.base.service.IService;
import com.core.toolbox.Record;
import com.shine.model.QueueType;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
public interface QueueTypeService extends IService<QueueType> {

	public List<Record> queryTriageName();

	public QueueType queryQueueTypeName(String queueTypeName);

	public QueueType findBySource_id(String source_id);
	//获取分诊台队列列表
	public List<Record> listQueueType(String ip);
	public List<Record> listQueueType2(String ip,String type);
	//获取分诊台叫号器列表
	public List<Record> listPager(String ip);
	public List<Record> listPager2(String ip,String type);
	//获取分诊台已登录叫号器列表
    public List<Record> listPagerLogin(String ip);
    public List<Record> listPagerLogin2(String ip);
    public List<Record> listPagerLogin2_all(String ip);
	public String FristPagerType(String id);

	public List<Record> listQueueTypeName(String ip);

	public List<Record> list_queue_type(String ip);
	public List<Record> list_queue_type_all(String ip);
	public List<Record> list_queue_type_pager(String ip);
	public List<Record> list_queue_type_pager_all(String ip);
	public List<Record> list_queue_type_pager_jz(String ip);
	
	public List<Record> list_queue_type_wait_call(String ip);
	public List<Record> list_queue_type_wait_call_pager(String ip);
	public List<Record> listPagerLogin2_pager(String ip) ;

	public List<Record> list_doctor_queuetype(String login_id);

	public List<Record> list_pager_queuetype(String login_id, String ip);

	public List<Record> findByQueueId(String queue_type_id);
	
	public Integer showloginupdate(String ip,String doctor_id);
	
	public Integer showloginupdateout(String ip);
	
	public Integer showcallupdate(String doctor_id,String source_id,String show_visiting,String show_wait,String show_visiting_nmb);
	
	public Record show_login(String ip) ;
	
	public Record show_call_door(String ip);
	
	public List<Record> show_call_hall(String ip);
	
	public List<Record> show_call_hall_type(String ip);
	
	public Integer showupdaecalled_door(String id);
	
	public Integer showupdaecalled_hall(String ids);
	
	public Integer showupdatequeuetype(String source_id,String name,String displayname);
	
	public Integer showupdatepager(String ip,String name,String displayname);
	
	public Integer showupdateterminal(String ip,String name,String displayname);
	
	public Integer showupdatepager2queue_type(String pager_id, String queue_type_id);
	
	public Integer showupdatepager2queue_type_del(String pager_id, String queue_type_id);
	
	public Integer showupdatepager2terminal(String pager_id, String id);
	
	public Integer showupdatepager2terminal_del(String pager_id, String id);
	
	public List<Record> showupdatepager2queue_type_list();
	
	public List<Record> showupdatepager2terminal_list();
	
	public Integer ResetCallStatus(String queue_type_id);
	
	
}
