package com.shine.service;

import java.util.List;

import com.core.base.service.IService;
import com.shine.model.Source;

/**
 * Generated by Blade. 2017-08-17 14:14:06
 */
public interface SourceService extends IService<Source> {

	public List<Source> listDesc();
}
