package com.shine.service;

import com.core.base.service.IService;
import com.shine.model.SyncDataLog;

/**
 * Generated by Blade. 2017-09-18 15:11:34
 */
public interface SyncDataLogService extends IService<SyncDataLog> {

	public int deletesyncdatalog();
	public void InsertLog(String log_name,String log_msg,String log_exception,Integer log_type);
}

