package com.shine.service;

import com.core.base.service.IService;
import com.core.toolbox.Record;
import com.shine.model.Terminal;

/**
 * Generated by Blade. 2017-08-12 15:10:04
 */
public interface TerminalService extends IService<Terminal> {

	public Terminal findbyip(String ip);

	public Record findbytriageip(String ip);
	
	public Record findtriageBytemIP(String ip);

	public String getpageripbyterip(String ip);
	
   public  void  addterminal(String ip,String name) ;
   
   public  int  edittriage(String ids,String triage_id);
}
