package com.shine.controller;

import com.core.jfinal.ext.kit.JsonKit;
import com.shine.model.Pager2queuetype;
import com.shine.service.Pager2queuetypeService;
import com.shine.service.impl.Pager2queuetypeServiceImpl;
import com.system.controller.base.UrlPermissController;

/**
 * Generated by Blade. 2017-08-09 15:50:39
 */
public class Pager2queuetypeController extends UrlPermissController {
	private static String CODE = "pager2queuetype";
	private static String PERFIX = "rlt_pager2queue_type";
	private static String LIST_SOURCE = "Pager2queuetype.list";
	private static String BASE_PATH = "/platform/pager2queuetype/";

	Pager2queuetypeService service = new Pager2queuetypeServiceImpl();

	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "pager2queuetype.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "pager2queuetype_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Pager2queuetype pager2queuetype = service.findById(id);
		setAttr("model", JsonKit.toJson(pager2queuetype));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "pager2queuetype_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Pager2queuetype pager2queuetype = service.findById(id);
		setAttr("model", JsonKit.toJson(pager2queuetype));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "pager2queuetype_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Pager2queuetype pager2queuetype = mapping(PERFIX, Pager2queuetype.class);
		boolean temp = service.save(pager2queuetype);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Pager2queuetype pager2queuetype = mapping(PERFIX, Pager2queuetype.class);

		boolean temp = service.update(pager2queuetype);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
