package com.shine.controller;

import com.core.jfinal.ext.kit.JsonKit;
import com.shine.model.Pager2terminal;
import com.shine.service.Pager2terminalService;
import com.shine.service.impl.Pager2terminalServiceImpl;
import com.system.controller.base.UrlPermissController;

/**
 * Generated by Blade. 2017-08-12 15:10:05
 */
public class Pager2terminalController extends UrlPermissController {
	private static String CODE = "pager2terminal";
	private static String PERFIX = "rlt_pager2terminal";
	private static String LIST_SOURCE = "Pager2terminal.list";
	private static String BASE_PATH = "/platform/pager2terminal/";

	Pager2terminalService service = new Pager2terminalServiceImpl();

	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "pager2terminal.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "pager2terminal_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Pager2terminal pager2terminal = service.findById(id);
		setAttr("model", JsonKit.toJson(pager2terminal));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "pager2terminal_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Pager2terminal pager2terminal = service.findById(id);
		setAttr("model", JsonKit.toJson(pager2terminal));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "pager2terminal_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Pager2terminal pager2terminal = mapping(PERFIX, Pager2terminal.class);
		boolean temp = service.save(pager2terminal);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Pager2terminal pager2terminal = mapping(PERFIX, Pager2terminal.class);

		boolean temp = service.update(pager2terminal);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
