package com.shine.controller;

import com.core.jfinal.ext.kit.JsonKit;
import com.shine.model.PatientCode;
import com.shine.service.PatientCodeService;
import com.shine.service.impl.PatientCodeServiceImpl;
import com.system.controller.base.UrlPermissController;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
public class PatientCodeController extends UrlPermissController {
	private static String CODE = "patientCode";
	private static String PERFIX = "patient_code";
	private static String LIST_SOURCE = "PatientCode.list";
	private static String BASE_PATH = "/platform/patientCode/";

	PatientCodeService service = new PatientCodeServiceImpl();

	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "patientCode.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "patientCode_add.html");
	}

	public void edit() {
		String id = getPara(0);
		PatientCode patientCode = service.findById(id);
		setAttr("model", JsonKit.toJson(patientCode));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "patientCode_edit.html");
	}

	public void view() {
		String id = getPara(0);
		PatientCode patientCode = service.findById(id);
		setAttr("model", JsonKit.toJson(patientCode));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "patientCode_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		PatientCode patientCode = mapping(PERFIX, PatientCode.class);
		boolean temp = service.save(patientCode);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		PatientCode patientCode = mapping(PERFIX, PatientCode.class);

		boolean temp = service.update(patientCode);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}

	public void deletecode() {
		service.deletecode();
	}
}
