package com.shine.controller;

import com.core.jfinal.ext.kit.JsonKit;
import com.shine.model.SyncDataLog;
import com.shine.service.SyncDataLogService;
import com.shine.service.impl.SyncDataLogServiceImpl;
import com.system.controller.base.UrlPermissController;

/**
 * Generated by Blade. 2017-09-18 15:11:34
 */
public class SyncDataLogController extends UrlPermissController {
	private static String CODE = "syncDataLog";
	private static String PERFIX = "sync_data_log";
	private static String LIST_SOURCE = "SyncDataLog.list";
	private static String BASE_PATH = "/platform/syncDataLog/";

	SyncDataLogService service = new SyncDataLogServiceImpl();

	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "syncDataLog.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "syncDataLog_add.html");
	}

	public void edit() {
		String id = getPara(0);
		SyncDataLog syncDataLog = service.findById(id);
		setAttr("model", JsonKit.toJson(syncDataLog));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "syncDataLog_edit.html");
	}

	public void view() {
		String id = getPara(0);
		SyncDataLog syncDataLog = service.findById(id);
		setAttr("model", JsonKit.toJson(syncDataLog));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "syncDataLog_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		SyncDataLog syncDataLog = mapping(PERFIX, SyncDataLog.class);
		boolean temp = service.save(syncDataLog);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		SyncDataLog syncDataLog = mapping(PERFIX, SyncDataLog.class);

		boolean temp = service.update(syncDataLog);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}

	public void deletelog() {
		int cnt = service.deletesyncdatalog();
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
	public void InserLog(String log_name,String log_msg,String log_exception,Integer log_type) {
		service.InsertLog(log_name, log_msg, log_exception, log_type);
	}
}
