package com.shine.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.core.annotation.BindID;
import com.core.model.BaseModel;

/**
 * Generated by Blade. 2017-08-16 09:50:09
 */
@Table(name = "data_connection")
@BindID(name = "id")
@SuppressWarnings("serial")
public class DataConnection extends BaseModel {
	private Integer id; // ID
	private String dbType; // 数据库类型
	private String description; // 描述
	private String password; // 密码
	private String username; // 用户名
	private String dbName;// 数据库名称
	private String url;// 连接地址
	private Integer err_type;
	private Integer doc_info;

	@AutoID
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDbType() {
		return dbType;
	}

	public void setDbType(String dbType) {
		this.dbType = dbType;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getDbName() {
		return dbName;
	}

	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	public Integer getErr_type() {
		return err_type;
	}

	public void setErr_type(Integer err_type) {
		this.err_type = err_type;
	}
	public Integer getDoc_info() {
		return doc_info;
	}

	public void setDoc_info(Integer doc_info) {
		this.doc_info = doc_info;
	}
}
