package com.shine.model;

import org.beetl.sql.core.annotatoin.Table;
import com.core.annotation.BindID;
import com.core.model.BaseModel;
import org.beetl.sql.core.annotatoin.AutoID;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
@Table(name = "doctor")
@BindID(name = "doctor_id")
@SuppressWarnings("serial")
public class Doctor extends BaseModel {
	private Integer doctor_id;
	private Integer db_source_id;
	private Integer p_doctor_id;
	private String call_rule;
	private String department;
	private String description;
	private String login_id;
	private String name;
	private String title;
	private String opr_time;

	@AutoID
	public Integer getDoctor_id() {
		return doctor_id;
	}

	public void setDoctor_id(Integer doctor_id) {
		this.doctor_id = doctor_id;
	}

	public Integer getDb_source_id() {
		return db_source_id;
	}

	public void setDb_source_id(Integer db_source_id) {
		this.db_source_id = db_source_id;
	}

	public Integer getP_doctor_id() {
		return p_doctor_id;
	}

	public void setP_doctor_id(Integer p_doctor_id) {
		this.p_doctor_id = p_doctor_id;
	}

	public String getCall_rule() {
		return call_rule;
	}

	public void setCall_rule(String call_rule) {
		this.call_rule = call_rule;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLogin_id() {
		return login_id;
	}

	public void setLogin_id(String login_id) {
		this.login_id = login_id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getOpr_time() {
		return opr_time;
	}

	public void setOpr_time(String opr_time) {
		this.opr_time = opr_time;
	}

}
