package com.shine.model;

import org.beetl.sql.core.annotatoin.Table;
import com.core.annotation.BindID;
import com.core.model.BaseModel;
import org.beetl.sql.core.annotatoin.AutoID;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
@Table(name = "rlt_doctor2queue_type")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Doctor2queuetype extends BaseModel {
	private Integer id;
	private Integer doctor_id;
	private Integer is_custom;
	private Integer queue_type_id;
	private String onduty;

	@AutoID
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDoctor_id() {
		return doctor_id;
	}

	public void setDoctor_id(Integer doctor_id) {
		this.doctor_id = doctor_id;
	}

	public Integer getIs_custom() {
		return is_custom;
	}

	public void setIs_custom(Integer is_custom) {
		this.is_custom = is_custom;
	}

	public Integer getQueue_type_id() {
		return queue_type_id;
	}

	public void setQueue_type_id(Integer queue_type_id) {
		this.queue_type_id = queue_type_id;
	}

	public String getOnduty() {
		return onduty;
	}

	public void setOnduty(String onduty) {
		this.onduty = onduty;
	}

}
