package com.shine.model;

import org.beetl.sql.core.annotatoin.Table;
import com.core.annotation.BindID;
import com.core.model.BaseModel;
import org.beetl.sql.core.annotatoin.AutoID;

/**
 * Generated by Blade. 2017-08-09 15:50:39
 */
@Table(name = "rlt_pager2queue_type")
@BindID(name = "pager_id,queue_type_id")
@SuppressWarnings("serial")
public class Pager2queuetype extends BaseModel {
	private Integer pager_id;
	private Integer queue_type_id;
	private Integer is_custom;
	private String onduty;

	@AutoID
	public Integer getPager_id() {
		return pager_id;
	}

	public void setPager_id(Integer pager_id) {
		this.pager_id = pager_id;
	}

	@AutoID
	public Integer getQueue_type_id() {
		return queue_type_id;
	}

	public void setQueue_type_id(Integer queue_type_id) {
		this.queue_type_id = queue_type_id;
	}

	public Integer getIs_custom() {
		return is_custom;
	}

	public void setIs_custom(Integer is_custom) {
		this.is_custom = is_custom;
	}

	public String getOnduty() {
		return onduty;
	}

	public void setOnduty(String onduty) {
		this.onduty = onduty;
	}

}
