package com.shine.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.core.annotation.BindID;
import com.core.model.BaseModel;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
@Table(name = "patient_queue")
@BindID(name = "id")
@SuppressWarnings("serial")
public class PatientQueue extends BaseModel {
	private Integer id;
	private Integer call_count;
	private Integer db_source_id;
	private Integer doctor_id;
	private Integer is_deleted;
	private Integer is_display;
	private Integer is_priority;
	private Integer operator_type;
	private Integer pager_id;
	private Integer parent_id;
	private Integer queue_type_id;
	private Integer return_flag;
	private Integer source_id;
	private Integer state_patient;
	private Integer sub_queue_order;
	private Integer time_interval;
	private String caller;
	private String content;
	private String istype;
	private String opr_time;
	private String patient_id;
	private String patient_name;
	private String queue_num;
	private String queue_type_source_id;
	private String register_id;
	private String state_custom;
	private String sub_queue_type;
	private Date call_time;
	private Date delay_time;
	private Date fre_date;
	private Date start_time;
	private String patient_source_code;

	@AutoID
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCall_count() {
		return call_count;
	}

	public void setCall_count(Integer call_count) {
		this.call_count = call_count;
	}

	public Integer getDb_source_id() {
		return db_source_id;
	}

	public void setDb_source_id(Integer db_source_id) {
		this.db_source_id = db_source_id;
	}

	public Integer getDoctor_id() {
		return doctor_id;
	}

	public void setDoctor_id(Integer doctor_id) {
		this.doctor_id = doctor_id;
	}

	public Integer getIs_deleted() {
		return is_deleted;
	}

	public void setIs_deleted(Integer is_deleted) {
		this.is_deleted = is_deleted;
	}

	public Integer getIs_display() {
		return is_display;
	}

	public void setIs_display(Integer is_display) {
		this.is_display = is_display;
	}

	public Integer getIs_priority() {
		return is_priority;
	}

	public void setIs_priority(Integer is_priority) {
		this.is_priority = is_priority;
	}

	public Integer getOperator_type() {
		return operator_type;
	}

	public void setOperator_type(Integer operator_type) {
		this.operator_type = operator_type;
	}

	public Integer getPager_id() {
		return pager_id;
	}

	public void setPager_id(Integer pager_id) {
		this.pager_id = pager_id;
	}

	public Integer getParent_id() {
		return parent_id;
	}

	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}

	public Integer getQueue_type_id() {
		return queue_type_id;
	}

	public void setQueue_type_id(Integer queue_type_id) {
		this.queue_type_id = queue_type_id;
	}

	public Integer getReturn_flag() {
		return return_flag;
	}

	public void setReturn_flag(Integer return_flag) {
		this.return_flag = return_flag;
	}

	public Integer getSource_id() {
		return source_id;
	}

	public void setSource_id(Integer source_id) {
		this.source_id = source_id;
	}

	public Integer getState_patient() {
		return state_patient;
	}

	public void setState_patient(Integer state_patient) {
		this.state_patient = state_patient;
	}

	public Integer getSub_queue_order() {
		return sub_queue_order;
	}

	public void setSub_queue_order(Integer sub_queue_order) {
		this.sub_queue_order = sub_queue_order;
	}

	public Integer getTime_interval() {
		return time_interval;
	}

	public void setTime_interval(Integer time_interval) {
		this.time_interval = time_interval;
	}

	public String getCaller() {
		return caller;
	}

	public void setCaller(String caller) {
		this.caller = caller;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getIstype() {
		return istype;
	}

	public void setIstype(String istype) {
		this.istype = istype;
	}

	public String getOpr_time() {
		return opr_time;
	}

	public void setOpr_time(String opr_time) {
		this.opr_time = opr_time;
	}

	public String getPatient_id() {
		return patient_id;
	}

	public void setPatient_id(String patient_id) {
		this.patient_id = patient_id;
	}

	public String getPatient_name() {
		return patient_name;
	}

	public void setPatient_name(String patient_name) {
		this.patient_name = patient_name;
	}

	public String getQueue_num() {
		return queue_num;
	}

	public void setQueue_num(String queue_num) {
		this.queue_num = queue_num;
	}

	public String getQueue_type_source_id() {
		return queue_type_source_id;
	}

	public void setQueue_type_source_id(String queue_type_source_id) {
		this.queue_type_source_id = queue_type_source_id;
	}

	public String getRegister_id() {
		return register_id;
	}

	public void setRegister_id(String register_id) {
		this.register_id = register_id;
	}

	public String getState_custom() {
		return state_custom;
	}

	public void setState_custom(String state_custom) {
		this.state_custom = state_custom;
	}

	public String getSub_queue_type() {
		return sub_queue_type;
	}

	public void setSub_queue_type(String sub_queue_type) {
		this.sub_queue_type = sub_queue_type;
	}

	public Date getCall_time() {
		return call_time;
	}

	public void setCall_time(Date call_time) {
		this.call_time = call_time;
	}

	public Date getDelay_time() {
		return delay_time;
	}

	public void setDelay_time(Date delay_time) {
		this.delay_time = delay_time;
	}

	public Date getFre_date() {
		return fre_date;
	}

	public void setFre_date(Date fre_date) {
		this.fre_date = fre_date;
	}

	public Date getStart_time() {
		return start_time;
	}

	public void setStart_time(Date start_time) {
		this.start_time = start_time;
	}

	public String getPatient_source_code() {
		return patient_source_code;
	}

	public void setPatient_source_code(String patient_source_code) {
		this.patient_source_code = patient_source_code;
	}

}
