package com.shine.model;

import org.beetl.sql.core.annotatoin.Table;
import com.core.annotation.BindID;
import com.core.model.BaseModel;
import org.beetl.sql.core.annotatoin.AutoID;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
@Table(name = "patient_code")
@BindID(name = "id")
@SuppressWarnings("serial")
public class PatientCode extends BaseModel {
	private Integer id;
	private Integer patient_queue_id;
	private String code;

	@AutoID
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPatient_queue_id() {
		return patient_queue_id;
	}

	public void setPatient_queue_id(Integer patient_queue_id) {
		this.patient_queue_id = patient_queue_id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
