package com.shine.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.core.annotation.BindID;
import com.core.model.BaseModel;
import com.core.toolbox.support.DateTime;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
@Table(name = "queue_type")
@BindID(name = "queue_type_id")
@SuppressWarnings("serial")
public class QueueType extends BaseModel {
	private Integer queue_type_id;
	private Integer avg_minute;
	private Integer db_source_id;
	private Integer is_checkin;
	private Integer is_pretriage;
	private Integer is_reorder;
	private Integer is_reserve;
	private Integer is_ckin_order;
	/*
	 * private Integer pass_first_flag; private Integer pass_flag_step;
	 */
	private Integer pass_max;
	/*
	 * private Integer agin_flag_step; private Integer agin_first_flag;
	 */
	private Integer triage_id;
	private String displayname;
	private String name;
	private Double queue_num_call_max;
	private Double queue_num_max;
	private String reserve_numlist;
	private String source_id;
	private String opr_time;
	private String floor;
	
	private String show_visiting;
	private String show_wait;
	private Integer show_call1;	
	private Integer show_call2;
	private Integer show_call3;
	private Integer show_call4;
	private String show_login;
	private DateTime show_call_time;	
	private DateTime show_login_time;	

	@AutoID
	public Integer getQueue_type_id() {
		return queue_type_id;
	}

	public void setQueue_type_id(Integer queue_type_id) {
		this.queue_type_id = queue_type_id;
	}

	public Integer getAvg_minute() {
		return avg_minute;
	}

	public void setAvg_minute(Integer avg_minute) {
		this.avg_minute = avg_minute;
	}

	public Integer getDb_source_id() {
		return db_source_id;
	}

	public void setDb_source_id(Integer db_source_id) {
		this.db_source_id = db_source_id;
	}

	public Integer getIs_checkin() {
		return is_checkin;
	}

	public void setIs_checkin(Integer is_checkin) {
		this.is_checkin = is_checkin;
	}

	
	public Integer getIs_pretriage() {
		return is_pretriage;
	}

	public void setIs_pretriage(Integer is_pretriage) {
		this.is_pretriage = is_pretriage;
	}

	public Integer getIs_reorder() {
		return is_reorder;
	}

	public void setIs_reorder(Integer is_reorder) {
		this.is_reorder = is_reorder;
	}

	public Integer getIs_ckin_order() {
		return is_ckin_order;
	}

	public void setIs_ckin_order(Integer is_ckin_order) {
		this.is_ckin_order = is_ckin_order;
	}
	
	public Integer getIs_reserve() {
		return is_reserve;
	}

	public void setIs_reserve(Integer is_reserve) {
		this.is_reserve = is_reserve;
	}

	/*
	 * public Integer getPass_first_flag() { return pass_first_flag; }
	 * 
	 * public void setPass_first_flag(Integer pass_first_flag) {
	 * this.pass_first_flag = pass_first_flag; }
	 * 
	 * public Integer getPass_flag_step() { return pass_flag_step; }
	 * 
	 * public void setPass_flag_step(Integer pass_flag_step) { this.pass_flag_step =
	 * pass_flag_step; }
	 */

	public Integer getPass_max() {
		return pass_max;
	}

	public void setPass_max(Integer pass_max) {
		this.pass_max = pass_max;
	}

	public Integer getTriage_id() {
		return triage_id;
	}

	public void setTriage_id(Integer triage_id) {
		this.triage_id = triage_id;
	}

	public String getDisplayname() {
		return displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getQueue_num_call_max() {
		return queue_num_call_max;
	}

	public void setQueue_num_call_max(Double queue_num_call_max) {
		this.queue_num_call_max = queue_num_call_max;
	}

	public Double getQueue_num_max() {
		return queue_num_max;
	}

	public void setQueue_num_max(Double queue_num_max) {
		this.queue_num_max = queue_num_max;
	}

	public String getReserve_numlist() {
		return reserve_numlist;
	}

	public void setReserve_numlist(String reserve_numlist) {
		this.reserve_numlist = reserve_numlist;
	}

	public String getSource_id() {
		return source_id;
	}

	public void setSource_id(String source_id) {
		this.source_id = source_id;
	}

	public String getOpr_time() {
		return opr_time;
	}

	public void setOpr_time(String opr_time) {
		this.opr_time = opr_time;
	}

	public String getFloor() {
		return floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}
	
	
	
	
	public String getShowVisiting() {
		return show_visiting;
	}

	public void setShowVisiting(String show_visiting) {
		this.show_visiting = show_visiting;
	}
	
	public String getShowWait() {
		return show_wait;
	}

	public void setShowWait(String show_wait) {
		this.show_wait = show_wait;
	}
	
	public Integer getShowCall1() {
		return show_call1;
	}

	public void setShowCall1(Integer show_call1) {
		this.show_call1 = show_call1;
	}
	public Integer getShowCall2() {
		return show_call2;
	}

	public void setShowCall2(Integer show_call2) {
		this.show_call2 = show_call2;
	}
	public Integer getShowCall3() {
		return show_call3;
	}

	public void setShowCall3(Integer show_call3) {
		this.show_call3 = show_call3;
	}
	public Integer getShowCall4() {
		return show_call4;
	}

	public void setShowCall4(Integer show_call4) {
		this.show_call4 = show_call4;
	}
	
	public String getShowLogin() {
		return show_login;
	}

	public void setShowLogin(String show_login) {
		this.show_login = show_login;
	}
	public DateTime getShowCallTime() {
		return show_call_time;
	}

	public void setShowCallTime(DateTime show_call_time) {
		this.show_call_time = show_call_time;
	}
	public DateTime getShowLoginTime() {
		return show_login_time;
	}

	public void setShowLoginTime(DateTime show_login_time) {
		this.show_login_time = show_login_time;
	}
	/*
	 * public Integer getAgin_flag_step() { return agin_flag_step; }
	 * 
	 * public void setAgin_flag_step(Integer agin_flag_step) { this.agin_flag_step =
	 * agin_flag_step; } public Integer getAgin_first_flag() { return
	 * agin_first_flag; }
	 * 
	 * public void setAgin_first_flag(Integer agin_first_flag) {
	 * this.agin_first_flag = agin_first_flag; }
	 */
}
