package com.shine.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.Table;

import com.core.annotation.BindID;
import com.core.model.BaseModel;

import org.beetl.sql.core.annotatoin.AutoID;

/**
 * Generated by Blade. 2017-09-18 15:11:34
 */
@Table(name = "sync_data_log")
@BindID(name = "id")
@SuppressWarnings("serial")
public class SyncDataLog extends BaseModel {
	private Integer id;
	private Integer log_type;
	private String log_exception;
	private String log_msg;
	private String log_name;
	private Date log_time;

	@AutoID
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getLog_type() {
		return log_type;
	}

	public void setLog_type(Integer log_type) {
		this.log_type = log_type;
	}

	public String getLog_exception() {
		return log_exception;
	}

	public void setLog_exception(String log_exception) {
		this.log_exception = log_exception;
	}

	public String getLog_msg() {
		return log_msg;
	}

	public void setLog_msg(String log_msg) {
		this.log_msg = log_msg;
	}

	public String getLog_name() {
		return log_name;
	}

	public void setLog_name(String log_name) {
		this.log_name = log_name;
	}

	public Date getLog_time() {
		return log_time;
	}

	public void setLog_time(Date log_time) {
		this.log_time = log_time;
	}

}
