package com.shine.model;

import org.beetl.sql.core.annotatoin.Table;
import com.core.annotation.BindID;
import com.core.model.BaseModel;
import org.beetl.sql.core.annotatoin.AutoID;

/**
 * Generated by Blade. 2017-08-12 15:10:05
 */
@Table(name = "terminal")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Terminal extends BaseModel {
	private Integer id;
	private Integer triage_id;
	private String display_name;
	private String ip;
	private String name;

	@AutoID
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTriage_id() {
		return triage_id;
	}

	public void setTriage_id(Integer triage_id) {
		this.triage_id = triage_id;
	}

	public String getDisplay_name() {
		return display_name;
	}

	public void setDisplay_name(String display_name) {
		this.display_name = display_name;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
