package com.shine.model;

import java.util.Date;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;

import com.core.annotation.BindID;
import com.core.model.BaseModel;

/**
 * Generated by Blade. 2017-08-03 10:50:24
 */
@Table(name = "triage")
@BindID(name = "triage_id")
@SuppressWarnings("serial")
public class Triage extends BaseModel {
	private Integer triage_id;
	private Integer call_buffer;
	private Integer pager_type;
	private Integer reorder_type;
	private Integer return_flag_step;
	private Integer late_flag_step;
	private Integer triage_type;
	private String description;
	private String ip;
	private String name;
	private String triage_pwd;
	private Date create_time;
	private Integer print_type;
	private Integer pass_time;
	private Integer first_flag_step;
	private Integer late_type;
	private Integer late_time;
	private Integer late_show;
	@AutoID
	public Integer getTriage_id() {
		return triage_id;
	}
	
	public void setTriage_id(Integer triage_id) {
		this.triage_id = triage_id;
	}
	
	public Integer getFirst_flag_step() {
		return first_flag_step;
	}

	public void setFirst_flag_step(Integer first_flag_step) {
		this.first_flag_step = first_flag_step;
	}
	
	public Integer getCall_buffer() {
		return call_buffer;
	}

	public void setCall_buffer(Integer call_buffer) {
		this.call_buffer = call_buffer;
	}

	public Integer getPager_type() {
		return pager_type;
	}

	public void setPager_type(Integer pager_type) {
		this.pager_type = pager_type;
	}

	public Integer getReorder_type() {
		return reorder_type;
	}

	public void setReorder_type(Integer reorder_type) {
		this.reorder_type = reorder_type;
	}

	public Integer getReturn_flag_step() {
		return return_flag_step;
	}

	public void setReturn_flag_step(Integer return_flag_step) {
		this.return_flag_step = return_flag_step;
	}
	
	public Integer getLate_flag_step() {
		return late_flag_step;
	}

	public void setLate_flag_step(Integer late_flag_step) {
		this.late_flag_step = late_flag_step;
	}

	public Integer getTriage_type() {
		return triage_type;
	}

	public void setTriage_type(Integer triage_type) {
		this.triage_type = triage_type;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTriage_pwd() {
		return triage_pwd;
	}

	public void setTriage_pwd(String triage_pwd) {
		this.triage_pwd = triage_pwd;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
	public Integer getPrint_type() {
		return print_type;
	}

	public void setPrint_type(Integer print_type) {
		this.print_type = print_type;
	}
	public Integer getPass_time() {
		return pass_time;
	}

	public void setPass_time(Integer pass_time) {
		this.pass_time = pass_time;
	}
	public Integer getLate_type() {
		return late_type;
	}

	public void setLate_type(Integer late_type) {
		this.late_type = late_type;
	}
	public Integer getLate_time() {
		return late_time;
	}

	public void setLate_time(Integer late_time) {
		this.late_time = late_time;
	}
	public Integer getLate_show() {
		return late_show;
	}

	public void setLate_show(Integer late_show) {
		this.late_show = late_show;
	}
}
